use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use wasmparser::{ExternalKind, Operator, Parser, Payload, TypeRef, ValType};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let helpers_dir = Path::new(&manifest_dir).join("helpers");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed=helpers/src/lib.rs");
    println!("cargo:rerun-if-changed=helpers/src/arena.rs");
    println!("cargo:rerun-if-changed=helpers/src/string.rs");
    println!("cargo:rerun-if-changed=helpers/Cargo.toml");
    println!("cargo:rerun-if-changed=helpers/.cargo/config.toml");

    // Build the helpers crate for wasm32 on stable. Clear inherited RUSTFLAGS
    // (parent cargo sets x86 target-cpu flags that are meaningless for wasm32).
    let target_dir = out_dir.join("helpers-target");
    let status = Command::new("cargo")
        .args([
            "build",
            "--release",
            "--target",
            "wasm32-unknown-unknown",
            "--target-dir",
        ])
        .arg(target_dir.to_str().unwrap())
        .env_remove("RUSTFLAGS")
        .env_remove("CARGO_ENCODED_RUSTFLAGS")
        .current_dir(&helpers_dir)
        .status()
        .expect("failed to build helpers crate");
    assert!(status.success(), "helpers crate build failed");

    let wasm_path = target_dir.join("wasm32-unknown-unknown/release/tscc_helpers.wasm");
    let wasm_bytes = fs::read(&wasm_path).expect("failed to read helpers .wasm");
    let bundle = extract_bundle(&wasm_bytes);

    // Write one .bin per function and emit the consumer-facing Rust module.
    let mut out = String::from(
        "// Auto-generated by build.rs — do not edit.\n\
         // `ValType` is brought into scope by the including file (`precompiled.rs`).\n\n\
         pub struct CallSite {\n    \
             pub byte_offset: u32,\n    \
             pub original_callee: u32,\n    \
             pub uleb128_len: u8,\n\
         }\n\n\
         pub struct PrecompiledFunc {\n    \
             pub name: Option<&'static str>,\n    \
             pub params: &'static [ValType],\n    \
             pub results: &'static [ValType],\n    \
             pub locals: &'static [(u32, ValType)],\n    \
             pub body: &'static [u8],\n    \
             pub call_sites: &'static [CallSite],\n\
         }\n\n",
    );

    for (i, func) in bundle.funcs.iter().enumerate() {
        let bin_path = out_dir.join(format!("helper_{i}.wasm.bin"));
        fs::write(&bin_path, &func.body).unwrap();
    }

    out.push_str("pub static PRECOMPILED_FUNCS: &[PrecompiledFunc] = &[\n");
    for (i, func) in bundle.funcs.iter().enumerate() {
        let name = match &func.name {
            Some(n) => format!("Some(\"{n}\")"),
            None => "None".to_string(),
        };
        let params = format_val_type_slice(&func.params);
        let results = format_val_type_slice(&func.results);
        let locals = format_locals(&func.locals);
        let call_sites = format_call_sites(&func.call_sites);
        write!(
            out,
            "    PrecompiledFunc {{\n        \
                 name: {name},\n        \
                 params: {params},\n        \
                 results: {results},\n        \
                 locals: {locals},\n        \
                 body: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/helper_{i}.wasm.bin\")),\n        \
                 call_sites: {call_sites},\n    \
             }},\n",
        )
        .unwrap();
    }
    out.push_str("];\n");

    fs::write(out_dir.join("precompiled_helpers.rs"), &out).unwrap();
}

struct ExtractedBundle {
    funcs: Vec<ExtractedFunc>,
}

struct ExtractedFunc {
    /// `Some` if this function is exported under that name; `None` for
    /// compiler-inserted internals (memcpy, memset, etc.).
    name: Option<String>,
    params: Vec<ValType>,
    results: Vec<ValType>,
    locals: Vec<(u32, ValType)>,
    /// Raw bytes of the function body (everything after locals, including final End).
    body: Vec<u8>,
    /// Call instructions found in `body`. Callee indices are **internal**
    /// (helper-module function index minus import count). `byte_offset` points
    /// at the `0x10` opcode byte; the uleb128 immediate starts one byte later.
    call_sites: Vec<ExtractedCallSite>,
}

struct ExtractedCallSite {
    byte_offset: u32,
    original_callee: u32,
    uleb128_len: u8,
}

fn extract_bundle(wasm_bytes: &[u8]) -> ExtractedBundle {
    // First pass: collect all section data we need.
    let mut func_type_sigs: Vec<(Vec<ValType>, Vec<ValType>)> = Vec::new();
    let mut func_type_indices: Vec<u32> = Vec::new(); // per internal function
    let mut exports: Vec<(String, u32)> = Vec::new();
    let mut bodies: Vec<wasmparser::FunctionBody> = Vec::new();

    for payload in Parser::new(0).parse_all(wasm_bytes) {
        let payload = payload.expect("invalid wasm");
        match payload {
            Payload::TypeSection(reader) => {
                for group in reader {
                    let group = group.unwrap();
                    for sub in group.types() {
                        // All helper types should be plain function types (no GC / struct).
                        let composite = &sub.composite_type.inner;
                        match composite {
                            wasmparser::CompositeInnerType::Func(ft) => {
                                let params: Vec<ValType> = ft.params().to_vec();
                                let results: Vec<ValType> = ft.results().to_vec();
                                func_type_sigs.push((params, results));
                            }
                            _ => panic!("unexpected non-function composite type in helpers wasm"),
                        }
                    }
                }
            }
            Payload::ImportSection(reader) => {
                for import in reader {
                    let import = import.unwrap();
                    if matches!(import.ty, TypeRef::Func(_)) {
                        panic!(
                            "helpers wasm has function import '{}::{}' — renumberer cannot \
                             reconstruct imports in tscc output; make the helper self-contained",
                            import.module, import.name
                        );
                    }
                }
                // Globals/memories/tables don't enter the function index space.
            }
            Payload::FunctionSection(reader) => {
                for ty_idx in reader {
                    func_type_indices.push(ty_idx.unwrap());
                }
            }
            Payload::ExportSection(reader) => {
                for export in reader {
                    let export = export.unwrap();
                    if export.kind == ExternalKind::Func {
                        exports.push((export.name.to_string(), export.index));
                    }
                }
            }
            Payload::CodeSectionEntry(body) => bodies.push(body),
            _ => {}
        }
    }

    assert_eq!(
        bodies.len(),
        func_type_indices.len(),
        "function section and code section disagree on function count"
    );

    let mut export_name_by_internal: std::collections::HashMap<u32, String> =
        std::collections::HashMap::new();
    for (name, idx) in exports {
        export_name_by_internal.insert(idx, name);
    }

    let mut funcs = Vec::with_capacity(bodies.len());
    for (i, body) in bodies.iter().enumerate() {
        let ty_idx = func_type_indices[i] as usize;
        let (params, results) = func_type_sigs[ty_idx].clone();
        let name = export_name_by_internal.get(&(i as u32)).cloned();
        let (locals, raw_body, call_sites) = extract_body(body, wasm_bytes);
        funcs.push(ExtractedFunc {
            name,
            params,
            results,
            locals,
            body: raw_body,
            call_sites,
        });
    }

    ExtractedBundle { funcs }
}

fn extract_body(
    body: &wasmparser::FunctionBody,
    wasm_bytes: &[u8],
) -> (Vec<(u32, ValType)>, Vec<u8>, Vec<ExtractedCallSite>) {
    // Parse locals declarations via the typed reader (gives us ValType directly).
    let mut locals_reader = body.get_locals_reader().unwrap();
    let mut locals = Vec::new();
    let n = locals_reader.get_count();
    for _ in 0..n {
        let (count, vt) = locals_reader.read().unwrap();
        locals.push((count, vt));
    }

    // Body start = absolute offset where the operators section begins (after locals).
    // End = the close of the CodeSectionEntry payload.
    let op_reader = body.get_operators_reader().unwrap();
    let body_start = op_reader.original_position();
    let body_end = body.range().end;

    // Gather (absolute_offset, operator) pairs.
    let mut ops: Vec<(usize, Operator)> = Vec::new();
    for item in op_reader.into_iter_with_offsets() {
        let (op, offset) = item.unwrap();
        ops.push((offset, op));
    }

    // Build call-site list. For each Call, the next operator's offset gives us
    // the end of the uleb128 immediate.
    let mut call_sites = Vec::new();
    for (i, (off, op)) in ops.iter().enumerate() {
        if let Operator::Call { function_index } = op {
            let next_off = if i + 1 < ops.len() {
                ops[i + 1].0
            } else {
                body_end
            };
            let call_offset_rel = (*off - body_start) as u32;
            let uleb_len = (next_off - off - 1) as u8; // -1 for 0x10 opcode byte
            call_sites.push(ExtractedCallSite {
                byte_offset: call_offset_rel,
                original_callee: *function_index,
                uleb128_len: uleb_len,
            });
        }
    }

    let raw_body = wasm_bytes[body_start..body_end].to_vec();
    (locals, raw_body, call_sites)
}

fn format_val_type_slice(vs: &[ValType]) -> String {
    if vs.is_empty() {
        return "&[]".to_string();
    }
    let mut s = String::from("&[");
    for (i, v) in vs.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        s.push_str(&val_type_to_rust(*v));
    }
    s.push(']');
    s
}

fn format_locals(locals: &[(u32, ValType)]) -> String {
    if locals.is_empty() {
        return "&[]".to_string();
    }
    let mut s = String::from("&[");
    for (i, (n, v)) in locals.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        write!(s, "({n}, {})", val_type_to_rust(*v)).unwrap();
    }
    s.push(']');
    s
}

fn format_call_sites(sites: &[ExtractedCallSite]) -> String {
    if sites.is_empty() {
        return "&[]".to_string();
    }
    let mut s = String::from("&[");
    for (i, cs) in sites.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        write!(
            s,
            "CallSite {{ byte_offset: {}, original_callee: {}, uleb128_len: {} }}",
            cs.byte_offset, cs.original_callee, cs.uleb128_len
        )
        .unwrap();
    }
    s.push(']');
    s
}

fn val_type_to_rust(v: ValType) -> String {
    match v {
        ValType::I32 => "ValType::I32".to_string(),
        ValType::I64 => "ValType::I64".to_string(),
        ValType::F32 => "ValType::F32".to_string(),
        ValType::F64 => "ValType::F64".to_string(),
        ValType::V128 => "ValType::V128".to_string(),
        ValType::Ref(rt) => panic!("unexpected ref type {rt:?} in helpers wasm"),
    }
}
