use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use wasmparser::{ExternalKind, Parser, Payload};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let helpers_dir = Path::new(&manifest_dir).join("helpers");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Rerun if helper source changes
    println!("cargo:rerun-if-changed=helpers/src/lib.rs");
    println!("cargo:rerun-if-changed=helpers/src/arena.rs");
    println!("cargo:rerun-if-changed=helpers/src/string.rs");
    println!("cargo:rerun-if-changed=helpers/Cargo.toml");

    // Build the helpers crate for wasm32. Uses stable Rust.
    // Clear inherited RUSTFLAGS (parent cargo sets x86 target-cpu flags
    // which are meaningless for wasm32).
    let target_dir = out_dir.join("helpers-target");
    let status = Command::new("cargo")
        .args([
            "build",
            "--release",
            "--target",
            "wasm32-unknown-unknown",
            "--target-dir",
        ])
        .arg(target_dir.to_str().unwrap())
        .env_remove("RUSTFLAGS")
        .env_remove("CARGO_ENCODED_RUSTFLAGS")
        .current_dir(&helpers_dir)
        .status()
        .expect("failed to build helpers crate");

    assert!(status.success(), "helpers crate build failed");

    let wasm_path =
        target_dir.join("wasm32-unknown-unknown/release/tscc_helpers.wasm");

    let wasm_bytes = fs::read(&wasm_path).expect("failed to read helpers .wasm");
    let helpers = extract_helpers(&wasm_bytes);

    // Write individual .bin files for instruction bytes
    // Generate a Rust source file that maps helper names to (locals, instructions)
    let mut code = String::from(
        "// Auto-generated by build.rs — do not edit\n\n\
         pub fn precompiled_function(name: &str) -> Option<Function> {\n    \
             match name {\n",
    );

    for helper in &helpers {
        // Write instruction bytes to a .bin file
        let bin_path = out_dir.join(format!("{}.wasm.bin", helper.name));
        fs::write(&bin_path, &helper.instructions).unwrap();

        // Generate the locals array as a Rust literal
        let locals_literal: Vec<String> = helper
            .locals
            .iter()
            .map(|(count, vt)| {
                let vt_str = match vt {
                    0x7F => "ValType::I32",
                    0x7E => "ValType::I64",
                    0x7D => "ValType::F32",
                    0x7C => "ValType::F64",
                    other => panic!("unknown ValType byte: {other:#x}"),
                };
                format!("({count}, {vt_str})")
            })
            .collect();

        code.push_str(&format!(
            "        \"{}\" => {{\n\
             \x20           let mut func = Function::new(vec![{}]);\n\
             \x20           func.raw(include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{}.wasm.bin\")).iter().copied());\n\
             \x20           Some(func)\n\
             \x20       }}\n",
            helper.name,
            locals_literal.join(", "),
            helper.name,
        ));
    }

    code.push_str("        _ => None,\n    }\n}\n");
    fs::write(out_dir.join("precompiled_helpers.rs"), &code).unwrap();
}

struct ExtractedHelper {
    name: String,
    /// Locals as (count, valtype_byte) pairs.
    locals: Vec<(u32, u8)>,
    /// Raw instruction bytes (everything after locals declaration, including the End opcode).
    instructions: Vec<u8>,
}

fn extract_helpers(wasm_bytes: &[u8]) -> Vec<ExtractedHelper> {
    let mut exports: Vec<(String, u32)> = Vec::new();
    let mut num_imports = 0u32;
    type FuncBody = (Vec<(u32, u8)>, Vec<u8>);
    let mut bodies: Vec<FuncBody> = Vec::new();

    for payload in Parser::new(0).parse_all(wasm_bytes) {
        let payload = payload.expect("invalid wasm");
        match payload {
            Payload::ImportSection(reader) => {
                for _ in reader {
                    num_imports += 1;
                }
            }
            Payload::ExportSection(reader) => {
                for export in reader {
                    let export = export.unwrap();
                    if export.kind == ExternalKind::Func {
                        exports.push((export.name.to_string(), export.index));
                    }
                }
            }
            Payload::CodeSectionEntry(body) => {
                let mut reader = body.get_binary_reader();

                // Parse locals declarations
                let num_local_groups = reader.read_var_u32().unwrap();
                let mut locals = Vec::new();
                for _ in 0..num_local_groups {
                    let count = reader.read_var_u32().unwrap();
                    let vt_byte = reader.read_u8().unwrap();
                    locals.push((count, vt_byte));
                }

                // Remaining bytes are instructions (including final End)
                let remaining = reader.bytes_remaining();
                let instructions = reader.read_bytes(remaining).unwrap().to_vec();
                bodies.push((locals, instructions));
            }
            _ => {}
        }
    }

    let mut result = Vec::new();
    for (name, func_idx) in exports {
        if func_idx >= num_imports {
            let code_idx = (func_idx - num_imports) as usize;
            if code_idx < bodies.len() {
                let (locals, instructions) = bodies[code_idx].clone();
                result.push(ExtractedHelper {
                    name,
                    locals,
                    instructions,
                });
            }
        }
    }
    result
}
