use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use wasmparser::{
    ConstExpr, ElementItems, ElementKind, ExternalKind, Operator, Parser, Payload, TypeRef,
    ValType,
};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let helpers_dir = Path::new(&manifest_dir).join("helpers");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed=helpers/src/lib.rs");
    println!("cargo:rerun-if-changed=helpers/src/arena.rs");
    println!("cargo:rerun-if-changed=helpers/src/hash.rs");
    println!("cargo:rerun-if-changed=helpers/src/inline.rs");
    println!("cargo:rerun-if-changed=helpers/src/string.rs");
    println!("cargo:rerun-if-changed=helpers/Cargo.toml");
    println!("cargo:rerun-if-changed=helpers/.cargo/config.toml");

    // Build the helpers crate for wasm32 on stable. Clear inherited RUSTFLAGS
    // (parent cargo sets x86 target-cpu flags that are meaningless for wasm32).
    let target_dir = out_dir.join("helpers-target");
    let status = Command::new("cargo")
        .args([
            "build",
            "--release",
            "--target",
            "wasm32-unknown-unknown",
            "--target-dir",
        ])
        .arg(target_dir.to_str().unwrap())
        .env_remove("RUSTFLAGS")
        .env_remove("CARGO_ENCODED_RUSTFLAGS")
        .current_dir(&helpers_dir)
        .status()
        .expect("failed to build helpers crate");
    assert!(status.success(), "helpers crate build failed");

    let wasm_path = target_dir.join("wasm32-unknown-unknown/release/tscc_helpers.wasm");
    let wasm_bytes = fs::read(&wasm_path).expect("failed to read helpers .wasm");
    let bundle = extract_bundle(&wasm_bytes);

    let mut out = String::from(
        "// Auto-generated by build.rs — do not edit.\n\
         // `ValType` is brought into scope by the including file (`precompiled.rs`).\n\n\
         pub struct CallSite {\n    \
             pub byte_offset: u32,\n    \
             /// Helper-space function index: [0, import_count) = imports,\n    \
             /// [import_count, ..) = internals offset into PRECOMPILED_FUNCS.\n    \
             pub original_callee: u32,\n    \
             pub uleb128_len: u8,\n\
         }\n\n\
         pub struct CallIndirectSite {\n    \
             pub byte_offset: u32,\n    \
             pub original_type_idx: u32,\n    \
             pub type_uleb_len: u8,\n    \
             pub original_table_idx: u32,\n    \
             pub table_uleb_len: u8,\n\
         }\n\n\
         pub struct GlobalSite {\n    \
             /// Byte offset of the opcode (0x23 for global.get, 0x24 for global.set).\n    \
             pub byte_offset: u32,\n    \
             pub original_global_idx: u32,\n    \
             pub uleb128_len: u8,\n    \
             pub is_set: bool,\n\
         }\n\n\
         pub struct LocalSite {\n    \
             /// Byte offset of the opcode (0x20 get / 0x21 set / 0x22 tee).\n    \
             pub byte_offset: u32,\n    \
             pub original_idx: u32,\n    \
             pub uleb128_len: u8,\n\
         }\n\n\
         pub struct PrecompiledFunc {\n    \
             pub name: Option<&'static str>,\n    \
             pub params: &'static [ValType],\n    \
             pub results: &'static [ValType],\n    \
             pub locals: &'static [(u32, ValType)],\n    \
             pub body: &'static [u8],\n    \
             pub call_sites: &'static [CallSite],\n    \
             pub call_indirect_sites: &'static [CallIndirectSite],\n    \
             pub global_sites: &'static [GlobalSite],\n    \
             /// L_splice-only: byte offsets of every local op in the body.\n    \
             /// Empty for L_helper functions.\n    \
             pub local_sites: &'static [LocalSite],\n    \
             /// L_splice-only: body contains a `return` opcode.\n    \
             pub has_return: bool,\n    \
             /// L_splice-only: body contains a `br_table` opcode.\n    \
             pub has_br_table: bool,\n    \
             /// True iff this helper was authored via `tscc_inline!`. The\n    \
             /// splicer paste-inlines its body at every call site instead of\n    \
             /// emitting a real WASM function and a `Call` opcode.\n    \
             pub is_inline: bool,\n\
         }\n\n\
         pub struct DataSegment {\n    \
             pub offset: u32,\n    \
             pub bytes: &'static [u8],\n\
         }\n\n\
         pub struct TableMeta {\n    \
             pub min: u32,\n    \
             pub max: Option<u32>,\n\
         }\n\n\
         pub struct ElementSegment {\n    \
             pub offset: u32,\n    \
             pub func_indices: &'static [u32],\n\
         }\n\n\
         pub struct TypeSig {\n    \
             pub params: &'static [ValType],\n    \
             pub results: &'static [ValType],\n\
         }\n\n\
         pub struct ImportFunc {\n    \
             pub module: &'static str,\n    \
             pub name: &'static str,\n    \
             pub params: &'static [ValType],\n    \
             pub results: &'static [ValType],\n\
         }\n\n\
         #[derive(Clone, Copy)]\n\
         pub enum GlobalInit {\n    \
             I32(i32),\n    \
             I64(i64),\n    \
             F32(f32),\n    \
             F64(f64),\n\
         }\n\n\
         pub struct DeclaredGlobal {\n    \
             pub val_type: ValType,\n    \
             pub mutable: bool,\n    \
             pub init: GlobalInit,\n\
         }\n\n",
    );

    for (i, func) in bundle.funcs.iter().enumerate() {
        let bin_path = out_dir.join(format!("helper_{i}.wasm.bin"));
        fs::write(&bin_path, &func.body).unwrap();
    }
    for (i, seg) in bundle.data_segments.iter().enumerate() {
        let bin_path = out_dir.join(format!("helper_data_{i}.bin"));
        fs::write(&bin_path, &seg.bytes).unwrap();
    }

    out.push_str("pub static PRECOMPILED_FUNCS: &[PrecompiledFunc] = &[\n");
    for (i, func) in bundle.funcs.iter().enumerate() {
        let name = match &func.name {
            Some(n) => format!("Some(\"{n}\")"),
            None => "None".to_string(),
        };
        let params = format_val_type_slice(&func.params);
        let results = format_val_type_slice(&func.results);
        let locals = format_locals(&func.locals);
        let call_sites = format_call_sites(&func.call_sites);
        let call_indirect_sites = format_call_indirect_sites(&func.call_indirect_sites);
        let global_sites = format_global_sites(&func.global_sites);
        let local_sites = format_local_sites(&func.local_sites);
        let has_return = func.has_return;
        let has_br_table = func.has_br_table;
        let is_inline = func.is_inline;
        write!(
            out,
            "    PrecompiledFunc {{\n        \
                 name: {name},\n        \
                 params: {params},\n        \
                 results: {results},\n        \
                 locals: {locals},\n        \
                 body: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/helper_{i}.wasm.bin\")),\n        \
                 call_sites: {call_sites},\n        \
                 call_indirect_sites: {call_indirect_sites},\n        \
                 global_sites: {global_sites},\n        \
                 local_sites: {local_sites},\n        \
                 has_return: {has_return},\n        \
                 has_br_table: {has_br_table},\n        \
                 is_inline: {is_inline},\n    \
             }},\n",
        )
        .unwrap();
    }
    out.push_str("];\n\n");

    out.push_str("pub static PRECOMPILED_TYPES: &[TypeSig] = &[\n");
    for (params, results) in &bundle.types {
        let p = format_val_type_slice(params);
        let r = format_val_type_slice(results);
        writeln!(out, "    TypeSig {{ params: {p}, results: {r} }},").unwrap();
    }
    out.push_str("];\n\n");

    // PRECOMPILED_IMPORTS: function imports (module, name, signature). Their
    // indices in helper-space come first; internal funcs follow.
    out.push_str("pub static PRECOMPILED_IMPORTS: &[ImportFunc] = &[\n");
    for imp in &bundle.imports {
        let p = format_val_type_slice(&imp.params);
        let r = format_val_type_slice(&imp.results);
        writeln!(
            out,
            "    ImportFunc {{ module: \"{}\", name: \"{}\", params: {}, results: {} }},",
            imp.module, imp.name, p, r,
        )
        .unwrap();
    }
    out.push_str("];\n\n");

    // PRECOMPILED_GLOBALS: declared globals with init values. Helper code's
    // `global.get/set N` indexes into this table after adjusting for global
    // imports (of which our helpers have none — enforced by extractor).
    out.push_str("pub static PRECOMPILED_GLOBALS: &[DeclaredGlobal] = &[\n");
    for g in &bundle.globals {
        let init = match g.init {
            GlobalInitValue::I32(v) => format!("GlobalInit::I32({v})"),
            GlobalInitValue::I64(v) => format!("GlobalInit::I64({v})"),
            GlobalInitValue::F32(v) => format!("GlobalInit::F32({})", format_f32(v)),
            GlobalInitValue::F64(v) => format!("GlobalInit::F64({})", format_f64(v)),
        };
        writeln!(
            out,
            "    DeclaredGlobal {{ val_type: {}, mutable: {}, init: {} }},",
            val_type_to_rust(g.val_type),
            g.mutable,
            init,
        )
        .unwrap();
    }
    out.push_str("];\n\n");

    out.push_str("pub static PRECOMPILED_DATA: &[DataSegment] = &[\n");
    for (i, seg) in bundle.data_segments.iter().enumerate() {
        writeln!(
            out,
            "    DataSegment {{ offset: {}, bytes: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/helper_data_{i}.bin\")) }},",
            seg.offset,
        )
        .unwrap();
    }
    out.push_str("];\n\n");

    match &bundle.table {
        Some(t) => {
            let max = match t.max {
                Some(v) => format!("Some({v})"),
                None => "None".to_string(),
            };
            writeln!(
                out,
                "pub static PRECOMPILED_TABLE: Option<TableMeta> = Some(TableMeta {{ min: {}, max: {} }});\n",
                t.min, max,
            )
            .unwrap();
        }
        None => {
            out.push_str("pub static PRECOMPILED_TABLE: Option<TableMeta> = None;\n\n");
        }
    }

    out.push_str("pub static PRECOMPILED_ELEMENTS: &[ElementSegment] = &[\n");
    for seg in &bundle.elements {
        let idxs = format_u32_slice(&seg.func_indices);
        writeln!(
            out,
            "    ElementSegment {{ offset: {}, func_indices: {} }},",
            seg.offset, idxs,
        )
        .unwrap();
    }
    out.push_str("];\n");

    fs::write(out_dir.join("precompiled_helpers.rs"), &out).unwrap();
}

struct ExtractedBundle {
    funcs: Vec<ExtractedFunc>,
    types: Vec<(Vec<ValType>, Vec<ValType>)>,
    imports: Vec<ExtractedImport>,
    globals: Vec<ExtractedGlobal>,
    data_segments: Vec<DataSegment>,
    table: Option<TableMeta>,
    elements: Vec<ElementSegment>,
}

struct ExtractedFunc {
    name: Option<String>,
    params: Vec<ValType>,
    results: Vec<ValType>,
    locals: Vec<(u32, ValType)>,
    body: Vec<u8>,
    call_sites: Vec<ExtractedCallSite>,
    call_indirect_sites: Vec<ExtractedCallIndirectSite>,
    global_sites: Vec<ExtractedGlobalSite>,
    /// L_splice-only: byte offsets and immediate widths for every
    /// `local.get`/`local.set`/`local.tee` in the body. Empty for L_helper
    /// functions (we never need to renumber their locals — `Call(idx)` is
    /// emitted unmodified). Recorded once at extraction time so splice.rs
    /// stays a pure byte-rewriter at runtime.
    local_sites: Vec<ExtractedLocalSite>,
    /// L_splice-only: true iff body contains `return`. Splicer rewrites these
    /// to `Br(0)` against the wrapping block. POC subset rejects helpers
    /// where this is true.
    has_return: bool,
    /// L_splice-only: true iff body contains `br_table`. POC subset rejects.
    has_br_table: bool,
    /// True iff this function was authored via `tscc_inline!` (L_splice).
    /// Detected by a custom-section marker emitted by the macro; see
    /// `crates/tscc/helpers/src/lib.rs`.
    is_inline: bool,
}

struct ExtractedImport {
    module: String,
    name: String,
    params: Vec<ValType>,
    results: Vec<ValType>,
}

struct ExtractedGlobal {
    val_type: ValType,
    mutable: bool,
    init: GlobalInitValue,
}

enum GlobalInitValue {
    I32(i32),
    I64(i64),
    F32(f32),
    F64(f64),
}

struct ExtractedCallSite {
    byte_offset: u32,
    /// Full helper-space function index (imports then internal).
    original_callee: u32,
    uleb128_len: u8,
}

struct ExtractedCallIndirectSite {
    byte_offset: u32,
    original_type_idx: u32,
    type_uleb_len: u8,
    original_table_idx: u32,
    table_uleb_len: u8,
}

struct ExtractedGlobalSite {
    byte_offset: u32,
    original_global_idx: u32,
    uleb128_len: u8,
    is_set: bool,
}

struct ExtractedLocalSite {
    byte_offset: u32,
    original_idx: u32,
    uleb128_len: u8,
}

struct DataSegment {
    offset: u32,
    bytes: Vec<u8>,
}

struct TableMeta {
    min: u32,
    max: Option<u32>,
}

struct ElementSegment {
    offset: u32,
    func_indices: Vec<u32>,
}

fn extract_bundle(wasm_bytes: &[u8]) -> ExtractedBundle {
    let mut func_type_sigs: Vec<(Vec<ValType>, Vec<ValType>)> = Vec::new();
    let mut func_type_indices: Vec<u32> = Vec::new();
    let mut exports: Vec<(String, u32)> = Vec::new();
    let mut bodies: Vec<wasmparser::FunctionBody> = Vec::new();
    let mut imports: Vec<ExtractedImport> = Vec::new();
    let mut globals: Vec<ExtractedGlobal> = Vec::new();
    let mut data_segments: Vec<DataSegment> = Vec::new();
    let mut table: Option<TableMeta> = None;
    let mut elements: Vec<ElementSegment> = Vec::new();
    // Inline-helper marker custom sections are emitted by `tscc_inline!` as
    // `.custom_section.tscc_inline.<fn_name>`. lld preserves the prefix
    // verbatim; we strip it to recover the function name.
    const INLINE_MARKER_PREFIX: &str = ".custom_section.tscc_inline.";
    let mut inline_names: std::collections::HashSet<String> = std::collections::HashSet::new();

    // We need types BEFORE imports to resolve function-import signatures.
    // wasmparser preserves section order, and wasm modules always have Types
    // before Imports, so a single-pass loop is safe.
    for payload in Parser::new(0).parse_all(wasm_bytes) {
        let payload = payload.expect("invalid wasm");
        match payload {
            Payload::TypeSection(reader) => {
                for group in reader {
                    let group = group.unwrap();
                    for sub in group.types() {
                        let composite = &sub.composite_type.inner;
                        match composite {
                            wasmparser::CompositeInnerType::Func(ft) => {
                                let params: Vec<ValType> = ft.params().to_vec();
                                let results: Vec<ValType> = ft.results().to_vec();
                                func_type_sigs.push((params, results));
                            }
                            _ => panic!(
                                "unexpected non-function composite type in helpers wasm"
                            ),
                        }
                    }
                }
            }
            Payload::ImportSection(reader) => {
                for import in reader {
                    let import = import.unwrap();
                    match import.ty {
                        TypeRef::Func(type_idx) => {
                            let (params, results) = func_type_sigs[type_idx as usize].clone();
                            imports.push(ExtractedImport {
                                module: import.module.to_string(),
                                name: import.name.to_string(),
                                params,
                                results,
                            });
                        }
                        TypeRef::Global(_) => {
                            panic!(
                                "helpers wasm has global import '{}::{}' — not supported yet; use a function import instead",
                                import.module, import.name
                            );
                        }
                        TypeRef::Memory(_) | TypeRef::Table(_) | TypeRef::Tag(_) => {
                            panic!(
                                "helpers wasm has non-function import '{}::{}' — not supported",
                                import.module, import.name
                            );
                        }
                    }
                }
            }
            Payload::FunctionSection(reader) => {
                for ty_idx in reader {
                    func_type_indices.push(ty_idx.unwrap());
                }
            }
            Payload::TableSection(reader) => {
                for t in reader {
                    let t = t.unwrap();
                    assert!(
                        matches!(t.ty.element_type, wasmparser::RefType::FUNCREF),
                        "helpers wasm table is not funcref",
                    );
                    if table.is_some() {
                        panic!("helpers wasm declares multiple tables");
                    }
                    table = Some(TableMeta {
                        min: t.ty.initial as u32,
                        max: t.ty.maximum.map(|m| m as u32),
                    });
                }
            }
            Payload::GlobalSection(reader) => {
                for g in reader {
                    let g = g.unwrap();
                    let init = parse_global_init(&g.init_expr).unwrap_or_else(|| {
                        panic!("helper global has non-constant initializer")
                    });
                    globals.push(ExtractedGlobal {
                        val_type: g.ty.content_type,
                        mutable: g.ty.mutable,
                        init,
                    });
                }
            }
            Payload::ExportSection(reader) => {
                for export in reader {
                    let export = export.unwrap();
                    if export.kind == ExternalKind::Func {
                        exports.push((export.name.to_string(), export.index));
                    }
                }
            }
            Payload::DataSection(reader) => {
                for data in reader {
                    let data = data.unwrap();
                    match data.kind {
                        wasmparser::DataKind::Active {
                            memory_index,
                            offset_expr,
                        } => {
                            assert_eq!(
                                memory_index, 0,
                                "helpers wasm data segment targets memory {memory_index}",
                            );
                            let offset = const_expr_i32(&offset_expr)
                                .expect("data segment offset not i32.const");
                            data_segments.push(DataSegment {
                                offset: offset as u32,
                                bytes: data.data.to_vec(),
                            });
                        }
                        wasmparser::DataKind::Passive => {
                            panic!("passive data segment not supported");
                        }
                    }
                }
            }
            Payload::ElementSection(reader) => {
                for elem in reader {
                    let elem = elem.unwrap();
                    match elem.kind {
                        ElementKind::Active {
                            table_index,
                            offset_expr,
                        } => {
                            let table_index = table_index.unwrap_or(0);
                            assert_eq!(
                                table_index, 0,
                                "element segment targets table {table_index}",
                            );
                            let offset = const_expr_i32(&offset_expr)
                                .expect("element segment offset not i32.const");
                            let func_indices = match elem.items {
                                ElementItems::Functions(reader) => {
                                    let mut v = Vec::new();
                                    for idx in reader {
                                        v.push(idx.unwrap());
                                    }
                                    v
                                }
                                ElementItems::Expressions(_, _) => {
                                    panic!("element segment uses expression form");
                                }
                            };
                            elements.push(ElementSegment {
                                offset: offset as u32,
                                func_indices,
                            });
                        }
                        ElementKind::Passive | ElementKind::Declared => {
                            panic!("passive/declared element segment not supported");
                        }
                    }
                }
            }
            Payload::CodeSectionEntry(body) => bodies.push(body),
            Payload::CustomSection(reader) => {
                if let Some(fn_name) = reader.name().strip_prefix(INLINE_MARKER_PREFIX) {
                    inline_names.insert(fn_name.to_string());
                }
            }
            _ => {}
        }
    }

    assert_eq!(
        bodies.len(),
        func_type_indices.len(),
        "function section and code section disagree on function count"
    );

    let import_count = imports.len() as u32;

    let mut export_name_by_internal: std::collections::HashMap<u32, String> =
        std::collections::HashMap::new();
    for (name, idx) in exports {
        // Exports index into the total function space; subtract imports to
        // get a PRECOMPILED_FUNCS-relative index.
        if idx >= import_count {
            export_name_by_internal.insert(idx - import_count, name);
        }
    }

    let mut funcs = Vec::with_capacity(bodies.len());
    for (i, body) in bodies.iter().enumerate() {
        let ty_idx = func_type_indices[i] as usize;
        let (params, results) = func_type_sigs[ty_idx].clone();
        let name = export_name_by_internal.get(&(i as u32)).cloned();
        let is_inline = name.as_deref().is_some_and(|n| inline_names.contains(n));
        let (locals, raw_body, call_sites, call_indirect_sites, global_sites) =
            extract_body(body, wasm_bytes);
        // Splice metadata is only needed for inline helpers — skip the extra
        // op walk for L_helper bodies.
        let (local_sites, has_return, has_br_table) = if is_inline {
            extract_inline_metadata(body)
        } else {
            (Vec::new(), false, false)
        };
        funcs.push(ExtractedFunc {
            name,
            params,
            results,
            locals,
            body: raw_body,
            call_sites,
            call_indirect_sites,
            global_sites,
            local_sites,
            has_return,
            has_br_table,
            is_inline,
        });
    }

    // Catch a `tscc_inline!` marker whose function got DCE'd / renamed:
    // every name in `inline_names` must correspond to an extracted function.
    for marked in &inline_names {
        if !funcs.iter().any(|f| f.name.as_deref() == Some(marked.as_str())) {
            panic!(
                "tscc_inline marker `{marked}` has no matching exported function in \
                 helpers wasm — check the macro invocation or LTO settings"
            );
        }
    }

    ExtractedBundle {
        funcs,
        types: func_type_sigs,
        imports,
        globals,
        data_segments,
        table,
        elements,
    }
}

fn const_expr_i32(expr: &ConstExpr) -> Option<i32> {
    let mut reader = expr.get_operators_reader();
    let op = reader.read().ok()?;
    let v = match op {
        Operator::I32Const { value } => value,
        _ => return None,
    };
    match reader.read().ok()? {
        Operator::End => {}
        _ => return None,
    }
    Some(v)
}

fn parse_global_init(expr: &ConstExpr) -> Option<GlobalInitValue> {
    let mut reader = expr.get_operators_reader();
    let op = reader.read().ok()?;
    let v = match op {
        Operator::I32Const { value } => GlobalInitValue::I32(value),
        Operator::I64Const { value } => GlobalInitValue::I64(value),
        Operator::F32Const { value } => GlobalInitValue::F32(f32::from_bits(value.bits())),
        Operator::F64Const { value } => GlobalInitValue::F64(f64::from_bits(value.bits())),
        _ => return None,
    };
    match reader.read().ok()? {
        Operator::End => {}
        _ => return None,
    }
    Some(v)
}

type ExtractedBodyParts = (
    Vec<(u32, ValType)>,
    Vec<u8>,
    Vec<ExtractedCallSite>,
    Vec<ExtractedCallIndirectSite>,
    Vec<ExtractedGlobalSite>,
);

fn extract_body(body: &wasmparser::FunctionBody, wasm_bytes: &[u8]) -> ExtractedBodyParts {
    let mut locals_reader = body.get_locals_reader().unwrap();
    let mut locals = Vec::new();
    let n = locals_reader.get_count();
    for _ in 0..n {
        let (count, vt) = locals_reader.read().unwrap();
        locals.push((count, vt));
    }

    let op_reader = body.get_operators_reader().unwrap();
    let body_start = op_reader.original_position();
    let body_end = body.range().end;

    let mut ops: Vec<(usize, Operator)> = Vec::new();
    for item in op_reader.into_iter_with_offsets() {
        let (op, offset) = item.unwrap();
        ops.push((offset, op));
    }

    let mut call_sites = Vec::new();
    let mut call_indirect_sites = Vec::new();
    let mut global_sites = Vec::new();
    for (i, (off, op)) in ops.iter().enumerate() {
        let next_off = if i + 1 < ops.len() {
            ops[i + 1].0
        } else {
            body_end
        };
        match op {
            Operator::Call { function_index } => {
                let rel = (*off - body_start) as u32;
                let uleb_len = (next_off - off - 1) as u8;
                call_sites.push(ExtractedCallSite {
                    byte_offset: rel,
                    original_callee: *function_index,
                    uleb128_len: uleb_len,
                });
            }
            Operator::CallIndirect {
                type_index,
                table_index,
            } => {
                let imm_start = off + 1;
                let imm_end = next_off;
                let imm_slice = &wasm_bytes[imm_start..imm_end];
                let (_, type_len) = decode_uleb128(imm_slice)
                    .expect("malformed call_indirect: bad type_idx uleb");
                let table_len = imm_slice.len() - type_len;
                assert!(table_len >= 1, "malformed call_indirect immediate");
                let rel = (*off - body_start) as u32;
                call_indirect_sites.push(ExtractedCallIndirectSite {
                    byte_offset: rel,
                    original_type_idx: *type_index,
                    type_uleb_len: type_len as u8,
                    original_table_idx: *table_index,
                    table_uleb_len: table_len as u8,
                });
            }
            Operator::GlobalGet { global_index } | Operator::GlobalSet { global_index } => {
                let is_set = matches!(op, Operator::GlobalSet { .. });
                let rel = (*off - body_start) as u32;
                let uleb_len = (next_off - off - 1) as u8;
                global_sites.push(ExtractedGlobalSite {
                    byte_offset: rel,
                    original_global_idx: *global_index,
                    uleb128_len: uleb_len,
                    is_set,
                });
            }
            _ => {}
        }
    }

    let raw_body = wasm_bytes[body_start..body_end].to_vec();
    (locals, raw_body, call_sites, call_indirect_sites, global_sites)
}

/// Splice-specific scan: enumerate every `local.get/set/tee` site (with
/// byte-offset + immediate width) and detect any unsupported control flow
/// the splicer would need extra work to handle. Only invoked for inline
/// helpers — splice metadata for L_helper functions stays empty.
fn extract_inline_metadata(
    body: &wasmparser::FunctionBody,
) -> (Vec<ExtractedLocalSite>, bool, bool) {
    let op_reader = body.get_operators_reader().unwrap();
    let body_start = op_reader.original_position();
    let body_end = body.range().end;

    let mut ops: Vec<(usize, Operator)> = Vec::new();
    for item in op_reader.into_iter_with_offsets() {
        let (op, offset) = item.unwrap();
        ops.push((offset, op));
    }

    let mut local_sites = Vec::new();
    let mut has_return = false;
    let mut has_br_table = false;
    for (i, (off, op)) in ops.iter().enumerate() {
        let next_off = if i + 1 < ops.len() {
            ops[i + 1].0
        } else {
            body_end
        };
        match op {
            Operator::LocalGet { local_index }
            | Operator::LocalSet { local_index }
            | Operator::LocalTee { local_index } => {
                let rel = (*off - body_start) as u32;
                let uleb_len = (next_off - off - 1) as u8;
                local_sites.push(ExtractedLocalSite {
                    byte_offset: rel,
                    original_idx: *local_index,
                    uleb128_len: uleb_len,
                });
            }
            Operator::Return => has_return = true,
            Operator::BrTable { .. } => has_br_table = true,
            _ => {}
        }
    }

    (local_sites, has_return, has_br_table)
}

fn decode_uleb128(bytes: &[u8]) -> Option<(u64, usize)> {
    let mut result: u64 = 0;
    let mut shift = 0u32;
    for (i, &byte) in bytes.iter().enumerate() {
        result |= u64::from(byte & 0x7f) << shift;
        if byte & 0x80 == 0 {
            return Some((result, i + 1));
        }
        shift += 7;
        if shift >= 64 {
            return None;
        }
    }
    None
}

fn format_val_type_slice(vs: &[ValType]) -> String {
    if vs.is_empty() {
        return "&[]".to_string();
    }
    let mut s = String::from("&[");
    for (i, v) in vs.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        s.push_str(&val_type_to_rust(*v));
    }
    s.push(']');
    s
}

fn format_locals(locals: &[(u32, ValType)]) -> String {
    if locals.is_empty() {
        return "&[]".to_string();
    }
    let mut s = String::from("&[");
    for (i, (n, v)) in locals.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        write!(s, "({n}, {})", val_type_to_rust(*v)).unwrap();
    }
    s.push(']');
    s
}

fn format_call_sites(sites: &[ExtractedCallSite]) -> String {
    if sites.is_empty() {
        return "&[]".to_string();
    }
    let mut s = String::from("&[");
    for (i, cs) in sites.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        write!(
            s,
            "CallSite {{ byte_offset: {}, original_callee: {}, uleb128_len: {} }}",
            cs.byte_offset, cs.original_callee, cs.uleb128_len
        )
        .unwrap();
    }
    s.push(']');
    s
}

fn format_call_indirect_sites(sites: &[ExtractedCallIndirectSite]) -> String {
    if sites.is_empty() {
        return "&[]".to_string();
    }
    let mut s = String::from("&[");
    for (i, cs) in sites.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        write!(
            s,
            "CallIndirectSite {{ byte_offset: {}, original_type_idx: {}, type_uleb_len: {}, original_table_idx: {}, table_uleb_len: {} }}",
            cs.byte_offset,
            cs.original_type_idx,
            cs.type_uleb_len,
            cs.original_table_idx,
            cs.table_uleb_len,
        )
        .unwrap();
    }
    s.push(']');
    s
}

fn format_local_sites(sites: &[ExtractedLocalSite]) -> String {
    if sites.is_empty() {
        return "&[]".to_string();
    }
    let mut s = String::from("&[");
    for (i, ls) in sites.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        write!(
            s,
            "LocalSite {{ byte_offset: {}, original_idx: {}, uleb128_len: {} }}",
            ls.byte_offset, ls.original_idx, ls.uleb128_len
        )
        .unwrap();
    }
    s.push(']');
    s
}

fn format_global_sites(sites: &[ExtractedGlobalSite]) -> String {
    if sites.is_empty() {
        return "&[]".to_string();
    }
    let mut s = String::from("&[");
    for (i, cs) in sites.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        write!(
            s,
            "GlobalSite {{ byte_offset: {}, original_global_idx: {}, uleb128_len: {}, is_set: {} }}",
            cs.byte_offset, cs.original_global_idx, cs.uleb128_len, cs.is_set
        )
        .unwrap();
    }
    s.push(']');
    s
}

fn format_u32_slice(vs: &[u32]) -> String {
    if vs.is_empty() {
        return "&[]".to_string();
    }
    let mut s = String::from("&[");
    for (i, v) in vs.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        write!(s, "{v}").unwrap();
    }
    s.push(']');
    s
}

fn format_f32(v: f32) -> String {
    if v.is_nan() {
        "f32::NAN".to_string()
    } else if v.is_infinite() {
        if v.is_sign_positive() {
            "f32::INFINITY".to_string()
        } else {
            "f32::NEG_INFINITY".to_string()
        }
    } else {
        // Emit as the bit pattern to preserve -0.0 and avoid lossy Debug formatting.
        format!("f32::from_bits({})", v.to_bits())
    }
}

fn format_f64(v: f64) -> String {
    if v.is_nan() {
        "f64::NAN".to_string()
    } else if v.is_infinite() {
        if v.is_sign_positive() {
            "f64::INFINITY".to_string()
        } else {
            "f64::NEG_INFINITY".to_string()
        }
    } else {
        format!("f64::from_bits({})", v.to_bits())
    }
}

fn val_type_to_rust(v: ValType) -> String {
    match v {
        ValType::I32 => "ValType::I32".to_string(),
        ValType::I64 => "ValType::I64".to_string(),
        ValType::F32 => "ValType::F32".to_string(),
        ValType::F64 => "ValType::F64".to_string(),
        ValType::V128 => "ValType::V128".to_string(),
        ValType::Ref(rt) => panic!("unexpected ref type {rt:?} in helpers wasm"),
    }
}
