pub(crate) mod array_builtins;
pub(crate) mod classes;
pub(crate) mod coerce;
pub(crate) mod dwarf;
pub(crate) mod expr;
pub(crate) mod func;
pub(crate) mod generics;
pub(crate) mod hash_builtins;
pub(crate) mod hash_table;
pub(crate) mod iterators;
pub(crate) mod map_builtins;
pub(crate) mod math_builtins;
pub(crate) mod module;
pub(crate) mod precompiled;
mod sections;
pub(crate) mod set_builtins;
pub(crate) mod shapes;
pub(crate) mod splice;
mod stmt;
pub(crate) mod string_builtins;
pub(crate) mod typed_arrays;
pub(crate) mod unions;
pub(crate) mod wasm_types;

pub(crate) use module::compile_module;
