// Pre-compiled WASM helpers built from Rust source in helpers/ crate.
// Generated by build.rs at compile time.

use wasm_encoder::{Function, ValType};

include!(concat!(env!("OUT_DIR"), "/precompiled_helpers.rs"));
